
module.exports = {
  'semi': [0, 'never'],
  'no-console': [0],
  'no-global-assign': [0],
  'eqeqeq': [1],
  'no-eval': [1],
  'no-undef': [1],
  'no-debugger': [1],
  'prefer-const': [1],
  'default-case': [1],
  'no-fallthrough': [1],
  'no-unused-vars': [1],
  'no-unreachable': [1],
  'no-new-wrappers': [1],
  'no-multi-spaces': [1],
  'no-sparse-arrays': [1],
  'no-constant-condition': [1],
  'quotes': [1, 'single'],
  'eol-last': [1, 'always'],
  'linebreak-style': [1, 'unix'],
  'indent': [1, 2, { 'SwitchCase': 1 }],
  'no-cond-assign': [1, 'except-parens'],
  'comma-dangle': [1, 'always-multiline'],
  'space-infix-ops': [1, { 'int32Hint': true }],
  'keyword-spacing': [1, { before: true, after: true }],
  'lines-around-comment': [1, {
    'beforeBlockComment': true,
  }],
}
